# .github/workflows/cypress.yml
name: Cypress Tests

on: 
  push:
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: configurar node
        uses: actions/setup-node@v2
        with:
          node-version: 13

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm install cypress

      - name: Install Cypress XPath
        run: npm install cypress-xpath

      - name: Run Cypress tests
        run: npx cypress run
