name: Pipe

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
 test:
 name: Pipeline de Testes Cypress
 runs-on: ubuntu-latest

 steps:
 - name: Checkout do código
 uses: actions/checkout@v2

 - name: Configurar o Node.js
 uses: actions/setup-node@v2
 
 with:
 node-version: 14
 - name: Instalar as dependências
 run: npm install

- name: Install Cypress XPath
run: npm install cypress-xpath

- name: Run Cypress tests
run: npm run cypress:run

 - name: Executar os testes
 run: npx cypress run